### ISSUE TITLE
Failed to activate the git-diff package

### ISSUE THREAD

**Issue by kmmbvnr** [atom/git-diff#106]
[Enter steps to reproduce below:]

1. Open a file in the fresh install of atom

**Atom Version**: 1.8.0
**System**: Ubuntu 15.10
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v1.1.0

### Stack Trace

Failed to activate the git-diff package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at GitDiffView.module.exports.GitDiffView.subscribeToRepository (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:129:48)
    at new GitDiffView (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:19:12)
    at /usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:23:9
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:307:9)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:22:29)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Atom v1.8.0 ships with git-diff v1.0.1. Please run `apm uninstall git-diff` if you have manually installed it. If you haven't manually installed the git-diff package, I suspect that you installed Atom from a Linux package manager that "customized" the Atom installation without doing proper testing. If so, please follow up with the maintainer of that customized Atom version.

We'll be happy to support a standard version of Atom. You can get it from the website at https://atom.io.

**Comment by 50Wliu** [comment]
@kmmbvnr How did you install Atom?

**Comment by joelmukuthu** [comment]
I also had this issue with atom v1.8.0 and I only got it to go away by disabling the built-in git-diff package. Incidentally `apm ls` lists the built-in git-diff version as v1.1.0. I upgraded atom (from v1.6.3 or something, I didn't check before updating) to v1.8.0 by running the .deb file from https://atom.io/download/deb on Ubuntu 16.04. Any ideas?

### apm ls
 I have disabled all the community packages as well as git-diff.
```
$ apm ls
Built-in Atom Packages (89)
├── about@1.5.0
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.2
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.39.0
├── bracket-matcher@0.82.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.38.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.3
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.1
├── language-css@0.36.1
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.21.1
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.34.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.1
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.1
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.2
├── line-ending-selector@0.4.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.1
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.1
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.0
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (14) /home/jmu/.atom/packages
├── atom-beautify@0.29.9
├── editorconfig@1.4.1
├── emmet@2.4.3
├── highlight-selected@0.11.2
├── language-babel@2.32.0
├── linter@1.11.14
├── linter-csslint@1.3.2
├── linter-eslint@7.2.4
├── linter-scss-lint@3.0.4
├── local-history@3.3.0
├── minimap@4.24.7
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
└── minimap-highlight-selected@4.4.0

└── (empty)
```

### apm -v
```
$ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4
```

**Comment by apopa116** [comment]
Same issue here. I've installed Atom v1.8.0(atom-amd64.deb) from the official website.

**Comment by ad222kr** [comment]
I have the same issue. Installed Atom 1.8.0 from atom.io

**Comment by lee-dohm** [comment]
Thanks everyone, I'm looking into it now.

**Comment by lee-dohm** [comment]
For all receiving this error message, uninstall the version of Atom you're currently using and install the appropriate one from here:

https://github.com/atom/atom/releases/latest

**Comment by lee-dohm** [comment]
Since this is a symptom of a larger Issue, I'm going to close this again. You will want to subscribe to and follow the workaround instructions in https://github.com/atom/atom/issues/12182.
