### ISSUE TITLE
Failed to activate the git-diff package

### ISSUE THREAD

**Issue by udoyen** [atom/git-diff#107]
[Enter steps to reproduce below:]

1. create git repo on computer
2. add files and then commit
3. create and add remote repo
4. close and relaunch atom

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v1.1.0

### Stack Trace

Failed to activate the git-diff package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at GitDiffView.module.exports.GitDiffView.subscribeToRepository (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:129:48)
    at new GitDiffView (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:19:12)
    at /usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:23:9
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:307:9)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/main.js:22:29)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
emmet, v2.4.3
laravel, v0.7.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please re-download Atom 1.8.0.  Apologies for the inconvenience.
