### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

### ISSUE THREAD

**Issue by digelim** [atom/git-diff#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: elementary OS
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:131

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at GitDiffView.module.exports.GitDiffView.subscribeToRepository (/usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:129:48)
    at /usr/share/atom/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:22:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:263:29)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:948:41
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:30.2.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:09.9.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please re-install Atom 1.8.0.  Sorry for the inconvenience.
