### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by jonico** [atom/git-diff#126]
1. Create a conflict in a branch, open atom, resolve conflict and commit, keep atom open
2. Go to command line, switch to a different branch, get a similar conflict in the same file

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package 1.2.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:202

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/app.asar/src/decoration-manager.js:192:17)
    at TextEditor.module.exports.TextEditor.decorateMarker (/app.asar/src/text-editor.js:1687:37)
    at GitDiffView.module.exports.GitDiffView.markRange (/app.asar/node_modules/git-diff/lib/git-diff-view.js:197:19)
    at GitDiffView.module.exports.GitDiffView.addDecorations (/app.asar/node_modules/git-diff/lib/git-diff-view.js:177:16)
    at GitDiffView.module.exports.GitDiffView.updateDiffs (/app.asar/node_modules/git-diff/lib/git-diff-view.js:161:23)
    at /app.asar/node_modules/git-diff/lib/git-diff-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1368:25
```

### Commands

```
     -5:42.5.0 core:save (input.hidden-input)
     -0:06.8.0 github:resolve-file-as-theirs (span.github-FilePatchListView-path)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-linkwrap 1.2.0 
atom-markdown-wrapper 5.2.1 
github 0.0.0 
markdown-themeable-pdf 1.2.0 
```

**Comment by maxbrunsfeld** [comment]
A lot has changed since we've heard about this happening, so the issue  may have been fixed. If not, please feel free to open a new issue on [the main Atom repository](https://github.com/atom/atom), as we have [moved this code there](https://github.com/atom/atom/pull/17993). Thanks!
