### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by Lepeskin** [atom/git-diff#48]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v0.28.0

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516

TypeError: Cannot read property 'style' of undefined
  at [object Object].$.fn.isHidden (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:516:20)
  at [object Object].$.fn.isVisible (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:511:18)
  at GitDiffView.module.exports.GitDiffView.renderDiffs (/Users/dl1/.atom/packages/git-diff/lib/git-diff-view.coffee:109:27)
  at atom-text-editor.<anonymous> (/Users/dl1/.atom/packages/git-diff/lib/git-diff-view.coffee:1:1)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at [object Object].module.exports.React.createClass.componentDidUpdate (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:273:54)
  at CallbackQueue.mixInto.notifyAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/CallbackQueue.js:75:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactReconcileTransaction.js:88:26)
  at ReactReconcileTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:141:20)
  at ReactUpdatesFlushTransaction.mixInto.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:98:38)
  at Object.flushBatchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:176:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:214:42)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/Transaction.js:155:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactDefaultBatchingStrategy.js:70:19)
  at Object.enqueueUpdate (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactUpdates.js:209:22)
  at [object Object].ReactCompositeComponentMixin.replaceState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:878:20)
  at [object Object].ReactCompositeComponentMixin.setState (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:850:10)
  at [object Object].module.exports.React.createClass.focused (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:619:14)
  at [object Object].boundMethod [as focused] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at atom-text-editor.TextEditorElement.focused (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:199:55)

```

### Commands

```
     -7:53.2 core:save-as (atom-text-editor.editor)
     -6:30.7 grammar-selector:show (atom-text-editor.editor)
     -6:28.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -6:28.4 core:cancel (atom-text-editor.editor.mini)
 34x -6:26.1 core:backspace (atom-text-editor.editor)
  2x -5:55.3 editor:newline (atom-text-editor.editor)
  3x -5:45.9 core:backspace (atom-text-editor.editor)
  2x -5:20.9 core:move-left (atom-text-editor.editor)
     -5:19.2 core:move-right (atom-text-editor.editor)
 33x -5:17.2 core:backspace (atom-text-editor.editor)
     -4:39.2 core:select-all (atom-text-editor.editor)
     -4:38.0 core:copy (atom-text-editor.editor)
     -0:00.0 window:install-shell-commands (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-diff, v0.28.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
From the debugging output above ("Installed Packages" section) it seems that you have a super-old version of git-diff installed locally (v0.28.0). The current version of that package is v0.50.0. 

If you remove the local package, this should resolve itself.

**Comment by Lepeskin** [comment]
Thank you a lot!
Yes, very old piece of software, already uninstall, all ok now

-- 
Денис Лепескин/Denis Lepeskin
Операционный директор/Chief Operating Officer
АПР Групп Азия/APR Group Asia
BAIYUN DISTRICT, GUANGZHOU CITY , CHINA.
广州白云区石井潭村宝鸭北路100号石井创意园L02栋
Mobile: +86 135 702 73754
Office: +86 206 197 2909
QQ: 1750600807
skype: lepeskin
http://www.aprconsulting.ru
http://www.aprgroup.ru
