### ISSUE TITLE
Failed to load the git-diff package

### ISSUE THREAD

**Issue by danielravina** [atom/git-diff#64]
[Enter steps to reproduce below:]

1. Open a directory

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.2
**Thrown From**: [git-diff](https://github.com/atom/git-diff) package, v0.55.0

### Stack Trace

Failed to load the git-diff package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/helpers.coffee:1:6)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/helpers.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/git-diff-view.coffee:2:23)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/git-diff-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/main.coffee:1:15)
  at Object.<anonymous> (/Users/danielravina/.atom/packages/git-diff/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:188:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:638:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "my-theme-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.4
git-diff, v0.55.0
my-theme-syntax, v0.0.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Why is git diff an installed package on your machine? Are you developing on it? you likely need to run `apm install` in the git-diff dir, or remove it from your `~/.atom/packages` dir

**Comment by izuzak** [comment]
@danielravina Let us know if the advice above doesn't help :point_up:, I'm closing this for now. :v:

**Comment by danielravina** [comment]
That did it. Thanks!
