### ISSUE TITLE
Error getting status for undefined when no file is open

### ISSUE THREAD

**Issue by 50Wliu** [atom/git-diff#93]
Steps to reproduce:
1. Open Atom with no files open
2. Open dev tools
OR
1. Open Atom
2. Close tabs that are open
3. Open dev tools

Any time that no files are open within Atom, two errors get thrown:
```
Error getting status for undefined:(anonymous function) @ C:\Program Files\Atom\resources\app.asar\node_modules\status-bar\lib\git-view.js:352
C:\Program Files\Atom\resources\app.asar\node_modules\status-bar\lib\git-view.js:353 Error: String path is required.
    at Error (native)
    at C:\Program Files\Atom\resources\app.asar\src\git-repository-async.js:609:44
    at tryCallOne (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\lib\core.js:37:12)
    at C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\lib\core.js:103:15
    at flush (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\node_modules\asap\raw.js:50:29)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)(anonymous function) @ C:\Program Files\Atom\resources\app.asar\node_modules\status-bar\lib\git-view.js:353
```
and
```
Error: String path is required.
    at Error (native)
    at C:\Program Files\Atom\resources\app.asar\src\git-repository-async.js:609:44
    at tryCallOne (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\lib\core.js:37:12)
    at C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\lib\core.js:103:15
    at flush (C:\Program Files\Atom\resources\app.asar\node_modules\nodegit\node_modules\promisify-node\node_modules\nodegit-promise\node_modules\asap\raw.js:50:29)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

In addition, I have seen similar errors thrown even when files are in the editor, but usually those files have just been added to the file tree and/or moved around.  Still trying to find a consistent repro case for that.

Windows 10 x64, Atom 1.7.0-dev-579b6b7, safe mode.

/cc @joshaber: More nodegit fun!

**Comment by joshaber** [comment]
Thanks @50Wliu!
